# Generated by Django 3.1 on 2020-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('userid', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('odatde', models.DateField()),
            ],
        ),
    ]
